name: Database Migrations

on:
  push:
    branches: [main]
    paths:
      - 'supabase/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Verify Supabase CLI installation
        run: supabase --version

      - name: Run migrations
        run: |
          # This is a placeholder for the actual migration command
          # In a real setup, you would use the Supabase CLI to run migrations
          echo "Running migrations..."
          
          # Example of how to run migrations with Supabase CLI
          # supabase db push --db-url ${{ secrets.SUPABASE_DB_URL }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
          
      - name: Verify migrations
        run: |
          echo "Verifying migrations..."
          # Add verification steps here
          
      - name: Notify on success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Database Migrations Completed"
          SLACK_MESSAGE: "Database migrations have been successfully applied to the database."
          SLACK_COLOR: good
          
      - name: Notify on failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_TITLE: "Database Migrations Failed"
          SLACK_MESSAGE: "Database migrations have failed. Please check the logs for more information."
          SLACK_COLOR: danger
