name: Sync Repository

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Fetch latest changes
        run: |
          git fetch --all
          git pull origin main

      - name: Update dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u
          
      - name: Install dependencies
        run: |
          pnpm install
          
      - name: Run tests
        run: |
          pnpm test || true
          
      - name: Create Pull Request if changes
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update dependencies"
          title: "chore: update dependencies"
          body: |
            This PR updates dependencies to their latest versions.
            
            - Automated changes by GitHub Actions
            - Please review the changes before merging
          branch: "chore/update-dependencies"
          base: "main"
